### ISSUE TITLE
min files are not compiled

### ISSUE THREAD

**Issue by lekoala** [malvahq/vscode-plugin-dartsass#26] opened 2020-02-12 14:02 UTC
hi again @akkumar ,

i updated the plugin to the latest version and it seems that compiling min files is not working. i have this output now. Not sure what it means. the unminified css file is compiled properly.

```
stderr: C:\ProgramData\chocolatey\bin\sass.exe:1
(function (exports, require, module, __filename, __dirname) { MZ�
                                                                ^

SyntaxError: Invalid or unexpected token
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3

Last Compiled Time: 1581515948300.
```

**Comment by akkumar** [comment] 2020-02-12 14:25
Anything out of the ordinary ( ? !) that you have in the source files, say
use or include?

Or may be a non utf8 character may be?

Anything more you see in the console log of the plugin?

**Comment by lekoala** [comment] 2020-02-12 15:36
@akkumar I thought it could be linked to an out of date node.js executable (i tried to use zeit recently, and it wasn't working either because of that) but i updated to v 12 and it's not helping

but looking at the debug log, it shows this: Exec: node.exe C:\ProgramData\chocolatey\bin\sass.exe  ..some\path\sass\mybox.scss:..some\path\css\mybox.css launched with pid 17680
why would node.exe be in front of the sass.exe executable? I think this is what causing the issue.

```
About to compile ..some\path\sass\mybox.scss
DEBUG: Run: Cwd: ..some\root\www. Exec: C:\ProgramData\chocolatey\bin\sass.exe ..some\path\sass\mybox.scss:..some\path\css\mybox.css launched with pid 1880
DEBUG: Run: Cwd: ..some\root\www. Exec: node.exe C:\ProgramData\chocolatey\bin\sass.exe  ..some\path\sass\mybox.scss:..some\path\css\mybox.css launched with pid 17680
stderr: C:\ProgramData\choc
stderr: olatey\bin\sass.exe:1
MZ�
  
SyntaxError: Invalid or unexpected token
    at wrapSafe (internal/modules/cjs/loader.js:1071:16)
    at Module._compile (internal/modules/cjs/loader.js:1121:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1177:10)
    at Module.load
```

**Comment by akkumar** [comment] 2020-02-13 05:31
Regarding node.exe at the beginning, check #24 where a discussion is going
on regarding open windows etc.

Incorporated suggestions from the same.

I am no windows expert but relying on community feedback here.  Sorry.

**Comment by akkumar** [comment] 2020-02-13 05:33
Also as per #24 sassbinpath should be set to node_modules/sass/sass.js or
similar.

The issue contains the correct path though.

Let me know if that helps fix the issue

**Comment by lekoala** [comment] 2020-02-13 09:51
@akkumar you are right ! i didn't read the description of the setting properly, i was using the exe file, not the installation from npm.
it's still not working i get stuck at "about to transform...." step

```
About to compile mywebroot\www\themes\mythemename\sass\main.scss
DEBUG: Run: Cwd: mywebroot\www. Exec: node.exe C:\Users\tport\AppData\Roaming\npm\node_modules\sass\sass.js  themes\mythemename\sass\main.scss:themes\mythemename\css\main.css launched with pid 7872
DEBUG: About to autoprefix file mywebroot\www\themes\mythemename\css\main.css to mywebroot\www\themes\mythemename\css\main.css
DEBUG: About to transform mywebroot\www\themes\mythemename\css\main.css to mywebroot\www\themes\mythemename\css\main.css
```

any idea?

**Comment by akkumar** [comment] 2020-02-13 09:53
>  i get stuck at "about to transform...." step

You mean it is not generating the output file correctly ?

**Comment by lekoala** [comment] 2020-02-13 09:58
@akkumar  i mean, it's not going further than that. i have my main.css file, but no main.min file and the debug output is not saying anything about min files. if i save again, it just do these two steps: autoprefix and transform, but no min files

**Comment by lekoala** [comment] 2020-02-13 10:20
@akkumar ah but interesting, when using the watcher, it does create the min file. as a side effect, it also create a min file for any css file in the directory, not just the one being compiled so maybe it's a bit too much :-)
it's not creating source map for the minified file

**Comment by akkumar** [comment] 2020-02-13 10:40
>  the debug output is not saying anything about min files. if i save again, it just do these two steps: autoprefix and transform, but no min files

Either this is a regression introduced since 0.5.0 or been like this forever. So , "compileOnSave" with sassbinPath set was not generating .min.css files before. That is sorted now. 

v0.5.3 should have the fix.

**Comment by akkumar** [comment] 2020-02-13 10:42
> , when using the watcher, it does create the min file. as a side effect, it also create a min file (the "balloon.min.css" file) for any css file in the directory, not just the one being compiled so maybe it's a bit too much 

That seems to be chokidar on steroids :)  There is a setting called `ignoreInitial` for chokidar . May be one of the future releases will try to mitigate this.

**Comment by lekoala** [comment] 2020-02-13 10:51
@akkumar  yes it's fixed now i get min files on save and source map. i probably didn't notice before due to my incorrect sassbin path. so maybe the last difference is the source map missing for the minified file when compiled using the watcher

**Comment by akkumar** [comment] 2020-02-13 11:44
> so maybe the last difference is the source map missing for the minified file when compiled using the watcher

v0.5.4 (of the plugin) release that should have the fix generation of sourcemaps for minified files. 

Caveat: It does generate the sourcemap. 
But then again the `sources` field in sourcemap appear to be "$stdin" .  Can you help let me know if that is a problem though.

**Comment by akkumar** [comment] 2020-02-13 11:45
also,  can you help confirm if issue in #24 (about console windows appearing for sass watcher processes) has been fixed now as well.

**Comment by akkumar** [comment] 2020-02-13 13:37
> But then again the sources field in sourcemap appear to be "$stdin" . Can you help let me know if that is a problem though.

I am looking into this . The "$stdin" seems to come from the autoprefixer though. May be a fix over the weekend.

**Comment by akkumar** [comment] 2020-02-15 11:47
Tracking missing sourcemaps separately in #28 separately.

**Closed** 2020-02-15 11:47 UTC
